# Generated by Django 3.0.6 on 2020-05-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
