# Generated by Django 3.0.6 on 2020-05-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
    ]
